package com.contextsolutions.localagent.classifier

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

/**
 * Byte-exact comparison between the on-device Kotlin [WordPieceTokenizer] and
 * HuggingFace `distilbert-base-uncased`. This is the gate that prevents
 * silent tokenizer drift (CLAUDE.md inv. #13, M3 handoff §3) — without it, a
 * subtle change in normalization or punctuation handling would degrade
 * classifier quality with no error message.
 *
 * The fixture is generated by:
 *   classifier-training/.venv/bin/python \
 *     classifier-training/scripts/generate_tokenizer_fixture.py
 *
 * `vocab.txt` is loaded via the test classpath; AGP's test source set
 * (configured in `:androidApp/build.gradle.kts`) maps `src/main/assets/` and
 * `classifier-training/tests/fixtures/` onto the resource path so this test
 * runs from a plain `./gradlew :androidApp:test` without any device.
 */
class WordPieceTokenizerFixtureTest {

    private val json = Json { ignoreUnknownKeys = true }

    private val vocab: Vocab by lazy {
        val stream = checkNotNull(javaClass.classLoader?.getResourceAsStream("vocab.txt")) {
            "vocab.txt not found on test classpath. Check :androidApp test sourceSet wiring."
        }
        Vocab.fromLines(stream.bufferedReader(Charsets.UTF_8).lineSequence())
    }

    private val fixture: FixturePayload by lazy {
        val stream = checkNotNull(javaClass.classLoader?.getResourceAsStream("tokenizer_canonical_inputs.json")) {
            "tokenizer_canonical_inputs.json not found on test classpath. " +
                "Run `classifier-training/.venv/bin/python " +
                "classifier-training/scripts/generate_tokenizer_fixture.py` to regenerate."
        }
        json.decodeFromString(FixturePayload.serializer(), stream.bufferedReader(Charsets.UTF_8).readText())
    }

    @Test
    fun fixture_metadata_matches_kotlin_constants() {
        assertEquals("distilbert-base-uncased", fixture.tokenizer)
        assertEquals(WordPieceTokenizer.MAX_SEQUENCE_LENGTH, fixture.maxLength)
        assertEquals(30522, fixture.vocabSize)
        assertEquals(WordPieceTokenizer.CLS_ID, fixture.specialTokens.cls)
        assertEquals(WordPieceTokenizer.SEP_ID, fixture.specialTokens.sep)
        assertEquals(WordPieceTokenizer.PAD_ID, fixture.specialTokens.pad)
        assertEquals(WordPieceTokenizer.UNK_ID, fixture.specialTokens.unk)
        assertEquals(30522, vocab.size)
    }

    @Test
    fun every_canonical_fixture_matches_python_byte_for_byte() {
        val tokenizer = WordPieceTokenizer(vocab)
        val mismatches = mutableListOf<String>()
        for (entry in fixture.fixtures) {
            val output = when (entry.kind) {
                "single" -> tokenizer.encodeSingle(entry.textA)
                "pair" -> tokenizer.encodePair(
                    entry.textA,
                    requireNotNull(entry.textB) { "pair fixture '${entry.id}' missing text_b" },
                )
                else -> {
                    fail("unknown fixture kind '${entry.kind}' for '${entry.id}'")
                    return // unreachable; satisfies the compiler about output's type
                }
            }
            val expectedIds = entry.inputIds.map { it.toLong() }.toLongArray()
            val expectedMask = entry.attentionMask.map { it.toLong() }.toLongArray()
            if (!output.inputIds.contentEquals(expectedIds)) {
                mismatches += diffSummary("input_ids", entry, output.inputIds, expectedIds)
            }
            if (!output.attentionMask.contentEquals(expectedMask)) {
                mismatches += diffSummary("attention_mask", entry, output.attentionMask, expectedMask)
            }
        }
        assertTrue(
            "Tokenizer output drifted from Python reference on ${mismatches.size} fixture(s):\n" +
                mismatches.joinToString("\n\n"),
            mismatches.isEmpty(),
        )
    }

    private fun diffSummary(
        field: String,
        entry: FixtureEntry,
        actual: LongArray,
        expected: LongArray,
    ): String {
        val firstDivergence = (0 until minOf(actual.size, expected.size))
            .firstOrNull { actual[it] != expected[it] }
            ?: minOf(actual.size, expected.size)
        val window = (firstDivergence - 4).coerceAtLeast(0)..
            (firstDivergence + 8).coerceAtMost(actual.size - 1)
        return buildString {
            append("[${entry.id} kind=${entry.kind}] $field diverges at index $firstDivergence\n")
            append("  text_a=").append(entry.textA.take(80)).append("\n")
            entry.textB?.let { append("  text_b=").append(it.take(80)).append("\n") }
            append("  expected[$window] = ${expected.slice(window)}\n")
            append("  actual  [$window] = ${actual.slice(window)}")
        }
    }

    @Serializable
    private data class FixturePayload(
        val tokenizer: String,
        @kotlinx.serialization.SerialName("max_length") val maxLength: Int,
        @kotlinx.serialization.SerialName("vocab_size") val vocabSize: Int,
        @kotlinx.serialization.SerialName("special_tokens") val specialTokens: SpecialTokens,
        val fixtures: List<FixtureEntry>,
    )

    @Serializable
    private data class SpecialTokens(
        val cls: Int,
        val sep: Int,
        val pad: Int,
        val unk: Int,
    )

    @Serializable
    private data class FixtureEntry(
        val id: String,
        val kind: String,
        @kotlinx.serialization.SerialName("text_a") val textA: String,
        @kotlinx.serialization.SerialName("text_b") val textB: String?,
        @kotlinx.serialization.SerialName("input_ids") val inputIds: List<Int>,
        @kotlinx.serialization.SerialName("attention_mask") val attentionMask: List<Int>,
    )
}
