package com.contextsolutions.localagent.memory

import com.contextsolutions.localagent.classifier.Vocab
import com.contextsolutions.localagent.classifier.WordPieceTokenizer
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Byte-exact comparison between the on-device [WordPieceTokenizer] and
 * HuggingFace `bert-base-uncased` (the tokenizer
 * `sentence-transformers/all-MiniLM-L6-v2` ships).
 *
 * The DistilBERT and BERT base uncased tokenizers share the same WordPiece
 * vocabulary (verified by SHA-256 match in the Phase A export driver) — so
 * the existing `WordPieceTokenizer` should produce identical output for
 * both classifier and embedder inputs. This test pins that contract.
 *
 * Companion to `WordPieceTokenizerFixtureTest` (DistilBERT side); the
 * fixture is generated by `classifier-training/scripts/export_minilm_litert.py`.
 */
class MinilmTokenizerFixtureTest {

    private val json = Json { ignoreUnknownKeys = true }

    private val vocab: Vocab by lazy {
        val stream = checkNotNull(javaClass.classLoader?.getResourceAsStream("vocab.txt")) {
            "vocab.txt not found on test classpath"
        }
        Vocab.fromLines(stream.bufferedReader(Charsets.UTF_8).lineSequence())
    }

    private val fixture: FixturePayload by lazy {
        val stream = checkNotNull(
            javaClass.classLoader?.getResourceAsStream("minilm_tokenizer_canonical_inputs.json"),
        ) {
            "minilm_tokenizer_canonical_inputs.json not found on test classpath. " +
                "Run `classifier-training/.venv/bin/python " +
                "classifier-training/scripts/export_minilm_litert.py --int8` to regenerate."
        }
        json.decodeFromString(
            FixturePayload.serializer(),
            stream.bufferedReader(Charsets.UTF_8).readText(),
        )
    }

    @Test
    fun fixture_metadata_is_minilm_compatible() {
        assertEquals("sentence-transformers/all-MiniLM-L6-v2", fixture.tokenizer)
        assertEquals(WordPieceTokenizer.MAX_SEQUENCE_LENGTH, fixture.maxLength)
        assertEquals(30522, fixture.vocabSize)
        assertEquals(WordPieceTokenizer.CLS_ID, fixture.specialTokens.cls)
        assertEquals(WordPieceTokenizer.SEP_ID, fixture.specialTokens.sep)
        assertEquals(WordPieceTokenizer.PAD_ID, fixture.specialTokens.pad)
        assertEquals(WordPieceTokenizer.UNK_ID, fixture.specialTokens.unk)
    }

    @Test
    fun every_minilm_fixture_matches_python_byte_for_byte() {
        val tokenizer = WordPieceTokenizer(vocab)
        val mismatches = mutableListOf<String>()
        for (entry in fixture.fixtures) {
            val output = tokenizer.encodeSingle(entry.text)
            val expectedIds = entry.inputIds.map { it.toLong() }.toLongArray()
            val expectedMask = entry.attentionMask.map { it.toLong() }.toLongArray()
            if (!output.inputIds.contentEquals(expectedIds)) {
                mismatches += "[${entry.id}] input_ids drift\n  text=${entry.text}\n  " +
                    "expected=${expectedIds.take(16)}…\n  actual=  ${output.inputIds.take(16)}…"
            }
            if (!output.attentionMask.contentEquals(expectedMask)) {
                mismatches += "[${entry.id}] attention_mask drift"
            }
        }
        assertTrue(
            "MiniLM tokenizer drift on ${mismatches.size} fixture(s):\n" +
                mismatches.joinToString("\n\n"),
            mismatches.isEmpty(),
        )
    }

    @Serializable
    private data class FixturePayload(
        val tokenizer: String,
        @kotlinx.serialization.SerialName("max_length") val maxLength: Int,
        @kotlinx.serialization.SerialName("vocab_size") val vocabSize: Int,
        @kotlinx.serialization.SerialName("special_tokens") val specialTokens: SpecialTokens,
        val fixtures: List<FixtureEntry>,
    )

    @Serializable
    private data class SpecialTokens(
        val cls: Int,
        val sep: Int,
        val pad: Int,
        val unk: Int,
    )

    @Serializable
    private data class FixtureEntry(
        val id: String,
        val text: String,
        @kotlinx.serialization.SerialName("input_ids") val inputIds: List<Int>,
        @kotlinx.serialization.SerialName("attention_mask") val attentionMask: List<Int>,
    )
}
