package com.contextsolutions.mobileagent.agent

import com.contextsolutions.mobileagent.search.SearchSource

/**
 * In-memory representation of a single message in a conversation. Maps onto the
 * `messages` SQLDelight table (see `Conversations.sq`) but lives in commonMain so
 * the agent loop and prompt assembler don't have to thread `Messages` row types
 * through their signatures.
 *
 * The sealed hierarchy mirrors the four roles Gemma 4's chat template
 * understands: System, User, Assistant (which may carry an inline tool call),
 * and Tool (the result returned for a prior call). The persistence layer
 * collapses these back into a flat `role` string column on save.
 */
sealed interface ChatMessage {
    val text: String

    data class System(override val text: String) : ChatMessage

    /**
     * A user turn. [imageBytes] (PR #48) is a downscaled JPEG attached to *this*
     * turn only; it is ephemeral — sent to the model and shown in the live
     * bubble but never persisted, so it is always null on history loaded back
     * from the DB. A [ByteArray] member makes the generated equality
     * array-identity based; nothing depends on structural equality of User.
     */
    data class User(
        override val text: String,
        val imageBytes: ByteArray? = null,
    ) : ChatMessage

    /**
     * Assistant turn produced by the model. Carries any leading text the model
     * emitted plus an optional tool call. When [toolCall] is non-null the
     * assistant turn is *incomplete* — the agent loop must execute the tool
     * and resume generation before the user-facing reply is final.
     */
    data class Assistant(
        override val text: String = "",
        val toolCall: ToolCall? = null,
        /**
         * Citations attached to a final assistant turn after one or more
         * searches in this turn. Empty for plain-text turns and for assistant
         * turns that only emitted a tool call (the citations land on the
         * subsequent assistant message that consumed the tool result).
         */
        val citations: List<SearchSource> = emptyList(),
    ) : ChatMessage

    /** Tool result fed back into the model's context after a tool call. */
    data class Tool(
        val callId: String,
        val toolName: String,
        override val text: String,
        val isError: Boolean = false,
    ) : ChatMessage
}

/**
 * A single function call emitted by the model. [callId] is generated by the
 * agent loop (the model itself doesn't have to produce one) and used to pair
 * the call with its [ChatMessage.Tool] result in the conversation history.
 */
data class ToolCall(
    val callId: String,
    val name: String,
    val argumentsJson: String,
)

/** Structured payload extracted from `argumentsJson` for the `web_search` tool. */
data class WebSearchArguments(val query: String)
